import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import os from "os";
import { execSync } from "child_process";
import {
	findResearchTasks,
	buildResearchPrompt,
	applyBracketRefresh,
} from "../scripts/discover-events.js";

let tmpDataDir;
let tmpConfigDir;

function writeJson(filePath, data) {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function runBuildEvents() {
	execSync("node scripts/build-events.js", {
		cwd: process.cwd(),
		env: {
			...process.env,
			SPORTSYNC_DATA_DIR: tmpDataDir,
			SPORTSYNC_CONFIG_DIR: tmpConfigDir,
		},
	});
}

function readJson(filePath) {
	return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

beforeEach(() => {
	tmpDataDir = fs.mkdtempSync(path.join(os.tmpdir(), "bracket-data-"));
	tmpConfigDir = fs.mkdtempSync(path.join(os.tmpdir(), "bracket-config-"));
});

afterEach(() => {
	fs.rmSync(tmpDataDir, { recursive: true, force: true });
	fs.rmSync(tmpConfigDir, { recursive: true, force: true });
});

// ─── build-events.js bracket extraction ─────────────────────────────────────

describe("build-events.js bracket extraction", () => {
	it("writes brackets.json when a curated config has a tournament with bracket data", () => {
		const futureStart = new Date(Date.now() + 1 * 24 * 3600000).toISOString().split("T")[0];
		const futureEnd = new Date(Date.now() + 5 * 24 * 3600000).toISOString().split("T")[0];

		writeJson(path.join(tmpConfigDir, "esports-cs2-2026.json"), {
			name: "CS2 Major 2026",
			sport: "esports",
			autoGenerated: true,
			events: [
				{
					title: "Team A vs Team B",
					time: new Date(Date.now() + 2 * 3600000).toISOString(),
					norwegian: true,
				},
			],
			tournaments: [
				{
					id: "cs2-major-2026",
					name: "CS2 Major 2026",
					venue: "Stockholm, Sweden",
					startDate: futureStart,
					endDate: futureEnd,
					format: "Double Elimination",
					tier: "S-Tier",
					prizePool: "$1,000,000 USD",
					focusTeam: "NaVi",
					focusTeamRoster: ["s1mple", "electronic"],
					coach: "b1ad3",
					bracket: {
						playoffs: {
							format: "Double Elimination (Bo3)",
							upperBracket: [
								{
									round: "Round 1",
									matches: [
										{
											team1: "NaVi",
											team2: "FaZe",
											score: "2-1",
											winner: "NaVi",
											status: "completed",
										},
									],
								},
							],
							lowerBracket: [],
							grandFinal: { matches: [{ team1: "TBD", team2: "TBD", status: "pending" }] },
						},
						focusTeamPath: {
							team: "NaVi",
							status: "Upper Bracket Round 2",
							completed: [{ stage: "UB R1", opponent: "FaZe", result: "W 2-1" }],
							current: { stage: "UB R2", opponent: "TBD", status: "scheduled" },
							ifWin: "Upper Bracket Final",
							ifLose: "Lower Bracket",
						},
					},
				},
			],
		});

		runBuildEvents();

		const bracketsPath = path.join(tmpDataDir, "brackets.json");
		expect(fs.existsSync(bracketsPath)).toBe(true);

		const brackets = readJson(bracketsPath);
		expect(brackets).toHaveProperty("cs2-major-2026");
	});

	it("includes expected bracket metadata fields in brackets.json", () => {
		const futureStart = new Date(Date.now() + 1 * 24 * 3600000).toISOString().split("T")[0];
		const futureEnd = new Date(Date.now() + 5 * 24 * 3600000).toISOString().split("T")[0];

		writeJson(path.join(tmpConfigDir, "test-esports.json"), {
			name: "Test Esports 2026",
			sport: "esports",
			autoGenerated: true,
			events: [
				{
					title: "Match 1",
					time: new Date(Date.now() + 2 * 3600000).toISOString(),
				},
			],
			tournaments: [
				{
					id: "test-tourney",
					name: "Test Tourney",
					venue: "Oslo, Norway",
					startDate: futureStart,
					endDate: futureEnd,
					format: "GSL Groups",
					tier: "A-Tier",
					prizePool: "$50,000 USD",
					focusTeam: "Heroic",
					focusTeamRoster: ["cadiaN", "stavn"],
					coach: "ave",
					bracket: {
						groups: {
							A: {
								name: "Group A",
								format: "GSL (Bo1)",
								matches: [],
							},
						},
					},
				},
			],
		});

		runBuildEvents();

		const brackets = readJson(path.join(tmpDataDir, "brackets.json"));
		const entry = brackets["test-tourney"];

		expect(entry.name).toBe("Test Tourney");
		expect(entry.venue).toBe("Oslo, Norway");
		expect(entry.startDate).toBe(futureStart);
		expect(entry.endDate).toBe(futureEnd);
		expect(entry.format).toBe("GSL Groups");
		expect(entry.tier).toBe("A-Tier");
		expect(entry.prizePool).toBe("$50,000 USD");
		expect(entry.focusTeam).toBe("Heroic");
		expect(entry.focusTeamRoster).toEqual(["cadiaN", "stavn"]);
		expect(entry.coach).toBe("ave");
		expect(entry.bracket).toBeDefined();
		expect(entry.bracket.groups.A.name).toBe("Group A");
	});

	it("writes multiple brackets from multiple configs", () => {
		const futureStart = new Date(Date.now() + 1 * 24 * 3600000).toISOString().split("T")[0];
		const futureEnd = new Date(Date.now() + 5 * 24 * 3600000).toISOString().split("T")[0];

		const makeTourneyConfig = (id, name, configFile) => {
			writeJson(path.join(tmpConfigDir, configFile), {
				name,
				sport: "esports",
				autoGenerated: true,
				events: [
					{
						title: `${name} Match`,
						time: new Date(Date.now() + 2 * 3600000).toISOString(),
					},
				],
				tournaments: [
					{
						id,
						name,
						startDate: futureStart,
						endDate: futureEnd,
						bracket: { playoffs: { format: "Bo3" } },
					},
				],
			});
		};

		makeTourneyConfig("tourney-alpha", "Alpha Cup", "alpha.json");
		makeTourneyConfig("tourney-beta", "Beta Cup", "beta.json");

		runBuildEvents();

		const brackets = readJson(path.join(tmpDataDir, "brackets.json"));
		expect(Object.keys(brackets)).toHaveLength(2);
		expect(brackets).toHaveProperty("tourney-alpha");
		expect(brackets).toHaveProperty("tourney-beta");
		expect(brackets["tourney-alpha"].name).toBe("Alpha Cup");
		expect(brackets["tourney-beta"].name).toBe("Beta Cup");
	});

	it("does not write brackets.json when no tournament has bracket data", () => {
		writeJson(path.join(tmpConfigDir, "no-bracket.json"), {
			name: "No Bracket Tournament",
			sport: "esports",
			autoGenerated: true,
			events: [
				{
					title: "Match",
					time: new Date(Date.now() + 2 * 3600000).toISOString(),
				},
			],
			tournaments: [
				{
					id: "no-bracket-tourney",
					name: "No Bracket",
					startDate: "2026-03-01",
					endDate: "2026-03-05",
					// No bracket field
				},
			],
		});

		runBuildEvents();

		// brackets.json should NOT be written when no bracket data exists
		const bracketsPath = path.join(tmpDataDir, "brackets.json");
		expect(fs.existsSync(bracketsPath)).toBe(false);
	});

	it("skips tournaments with bracket but no id", () => {
		writeJson(path.join(tmpConfigDir, "no-id.json"), {
			name: "No ID Tournament",
			sport: "esports",
			autoGenerated: true,
			events: [
				{
					title: "Match",
					time: new Date(Date.now() + 2 * 3600000).toISOString(),
				},
			],
			tournaments: [
				{
					// No id field
					name: "No ID Tourney",
					startDate: "2026-03-01",
					endDate: "2026-03-05",
					bracket: { playoffs: { format: "Bo3" } },
				},
			],
		});

		runBuildEvents();

		// Should not write brackets.json for a tournament with no id
		const bracketsPath = path.join(tmpDataDir, "brackets.json");
		expect(fs.existsSync(bracketsPath)).toBe(false);
	});
});

// ─── findResearchTasks — refresh-bracket ────────────────────────────────────

describe("findResearchTasks() — refresh-bracket", () => {
	it("returns a refresh-bracket task for an active tournament with stale bracket data", () => {
		const now = new Date("2026-02-25T12:00:00Z");
		// Tournament active: started yesterday, ends tomorrow
		const startDate = "2026-02-24";
		const endDate = "2026-02-26";

		const configs = [
			{
				filename: "esports-cs2-2026.json",
				config: {
					name: "CS2 Major",
					sport: "esports",
					autoGenerated: true,
					// Non-empty events so this doesn't trigger a priority-2 new-config task
					events: [{ title: "Match 1", time: "2026-02-25T14:00:00Z" }],
					// lastResearched well before 4h threshold
					lastResearched: "2026-02-25T06:00:00Z",
					tournaments: [
						{
							id: "cs2-major",
							name: "CS2 Major",
							startDate,
							endDate,
							bracket: { playoffs: { format: "Double Elimination (Bo3)" } },
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		const bracketTask = tasks.find((t) => t.type === "refresh-bracket");
		expect(bracketTask).toBeDefined();
		expect(bracketTask.priority).toBe(4);
		expect(bracketTask.filename).toBe("esports-cs2-2026.json");
		expect(bracketTask.tournament.id).toBe("cs2-major");
		expect(bracketTask.reason).toContain("CS2 Major");
	});

	it("does not return refresh-bracket when bracket was refreshed less than 4h ago", () => {
		const now = new Date("2026-02-25T12:00:00Z");
		// lastResearched only 2 hours ago — within 4h window
		const lastResearched = new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString();

		const configs = [
			{
				filename: "esports-cs2-2026.json",
				config: {
					name: "CS2 Major",
					sport: "esports",
					autoGenerated: true,
					events: [],
					lastResearched,
					tournaments: [
						{
							id: "cs2-major",
							name: "CS2 Major",
							startDate: "2026-02-24",
							endDate: "2026-02-26",
							bracket: { playoffs: { format: "Double Elimination (Bo3)" } },
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		expect(tasks.every((t) => t.type !== "refresh-bracket")).toBe(true);
	});

	it("does not return refresh-bracket when the tournament has ended more than 2 days ago", () => {
		const now = new Date("2026-02-25T12:00:00Z");
		// Tournament ended 5 days ago
		const configs = [
			{
				filename: "old-tourney.json",
				config: {
					name: "Old Tourney",
					sport: "esports",
					autoGenerated: true,
					events: [],
					lastResearched: "2026-02-19T06:00:00Z",
					tournaments: [
						{
							id: "old-tourney",
							name: "Old Tourney",
							startDate: "2026-02-18",
							endDate: "2026-02-19",
							bracket: { playoffs: { format: "Double Elimination (Bo3)" } },
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		expect(tasks.every((t) => t.type !== "refresh-bracket")).toBe(true);
	});

	it("does not return refresh-bracket when tournament starts more than 2 days in the future", () => {
		const now = new Date("2026-02-25T12:00:00Z");
		// Tournament starts 10 days from now
		const configs = [
			{
				filename: "future-tourney.json",
				config: {
					name: "Future Tourney",
					sport: "esports",
					autoGenerated: true,
					events: [],
					tournaments: [
						{
							id: "future-tourney",
							name: "Future Tourney",
							startDate: "2026-03-07",
							endDate: "2026-03-12",
							bracket: { playoffs: { format: "Double Elimination (Bo3)" } },
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		expect(tasks.every((t) => t.type !== "refresh-bracket")).toBe(true);
	});

	it("does not return refresh-bracket when tournament has no bracket data", () => {
		const now = new Date("2026-02-25T12:00:00Z");

		const configs = [
			{
				filename: "no-bracket.json",
				config: {
					name: "No Bracket",
					sport: "esports",
					autoGenerated: true,
					events: [],
					tournaments: [
						{
							id: "no-bracket",
							name: "No Bracket",
							startDate: "2026-02-24",
							endDate: "2026-02-26",
							// No bracket field
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		expect(tasks.every((t) => t.type !== "refresh-bracket")).toBe(true);
	});

	it("returns refresh-bracket when lastResearched is null (never refreshed) for an active tournament", () => {
		const now = new Date("2026-02-25T12:00:00Z");

		const configs = [
			{
				filename: "fresh.json",
				config: {
					name: "Fresh Tourney",
					sport: "esports",
					// Not autoGenerated — prevents spurious priority-2 new-config task
					autoGenerated: false,
					events: [{ title: "Match", time: "2026-02-25T14:00:00Z" }],
					// No lastResearched at all
					tournaments: [
						{
							id: "fresh-tourney",
							name: "Fresh Tourney",
							startDate: "2026-02-24",
							endDate: "2026-02-26",
							bracket: { playoffs: { format: "Bo3" } },
						},
					],
				},
			},
		];

		const tasks = findResearchTasks(configs, null, now);
		const bracketTask = tasks.find((t) => t.type === "refresh-bracket");
		expect(bracketTask).toBeDefined();
	});
});

// ─── buildResearchPrompt — refresh-bracket ──────────────────────────────────

describe("buildResearchPrompt() — refresh-bracket", () => {
	it("returns a bracket-specific prompt when task.type is refresh-bracket", () => {
		const task = {
			type: "refresh-bracket",
			filename: "esports-cs2-2026.json",
			config: {
				name: "CS2 Major 2026",
				sport: "esports",
				norwegianTeams: ["100 Thieves"],
			},
			tournament: {
				id: "cs2-major-2026",
				name: "CS2 Major 2026",
				focusTeam: "100 Thieves",
				bracket: {
					playoffs: {
						format: "Double Elimination (Bo3)",
						upperBracket: [],
						lowerBracket: [],
					},
				},
			},
		};

		const prompt = buildResearchPrompt(task, null);

		expect(prompt).toContain("CS2 Major 2026");
		expect(prompt).toContain("100 Thieves");
		expect(prompt).toContain("HLTV");
		expect(prompt).toContain("bracket");
		expect(prompt).toContain("focusTeamPath");
		expect(prompt).toContain("completed");
		expect(prompt).toContain("scheduled");
	});

	it("includes instructions to search HLTV, Liquipedia, or dust2.us", () => {
		const task = {
			type: "refresh-bracket",
			filename: "esports-event.json",
			config: { name: "ESL Pro League", sport: "esports" },
			tournament: {
				id: "esl-pro-league",
				name: "ESL Pro League",
				bracket: {},
			},
		};

		const prompt = buildResearchPrompt(task, null);

		expect(prompt).toMatch(/HLTV|Liquipedia|dust2/);
	});

	it("includes the focusTeam from tournament.focusTeam in the bracket prompt", () => {
		const task = {
			type: "refresh-bracket",
			filename: "esports-event.json",
			config: { name: "IEM Cologne 2026", sport: "esports" },
			tournament: {
				id: "iem-cologne-2026",
				name: "IEM Cologne 2026",
				focusTeam: "Heroic",
				bracket: { groups: {} },
			},
		};

		const prompt = buildResearchPrompt(task, null);
		expect(prompt).toContain("Heroic");
	});

	it("falls back to config.norwegianTeams when tournament.focusTeam is absent", () => {
		const task = {
			type: "refresh-bracket",
			filename: "esports-event.json",
			config: {
				name: "BLAST Premier 2026",
				sport: "esports",
				norwegianTeams: ["Apeks"],
			},
			tournament: {
				id: "blast-premier-2026",
				name: "BLAST Premier 2026",
				// No focusTeam
				bracket: { playoffs: {} },
			},
		};

		const prompt = buildResearchPrompt(task, null);
		expect(prompt).toContain("Apeks");
	});

	it("includes the current bracket JSON in the prompt for context", () => {
		const bracket = {
			playoffs: {
				format: "Double Elimination (Bo3)",
				upperBracket: [{ round: "Round 1", matches: [] }],
			},
		};

		const task = {
			type: "refresh-bracket",
			filename: "esports-event.json",
			config: { name: "Test Event", sport: "esports" },
			tournament: {
				id: "test-event",
				name: "Test Event",
				focusTeam: "TeamX",
				bracket,
			},
		};

		const prompt = buildResearchPrompt(task, null);
		expect(prompt).toContain("Double Elimination (Bo3)");
	});
});

// ─── buildResearchPrompt — esports-specific schema ──────────────────────────

describe("buildResearchPrompt() — esports schema", () => {
	it("includes bracket schema fields in the JSON schema when sport is esports", () => {
		const task = {
			type: "new-config",
			filename: "esports-test.json",
			config: {
				name: "IEM Katowice 2026",
				sport: "esports",
				events: [],
				norwegianTeams: ["NaVi"],
			},
		};

		const prompt = buildResearchPrompt(task, null);

		expect(prompt).toContain("bracket");
		expect(prompt).toContain("focusTeamPath");
		expect(prompt).toContain("upperBracket");
		expect(prompt).toContain("lowerBracket");
		expect(prompt).toContain("grandFinal");
	});

	it("includes esports event fields (format, stage, result) when sport is esports", () => {
		const task = {
			type: "new-config",
			filename: "esports-epl.json",
			config: {
				name: "ESL Pro League Season 23",
				sport: "esports",
				events: [],
			},
		};

		const prompt = buildResearchPrompt(task, null);

		expect(prompt).toContain("Bo1|Bo3|Bo5");
		expect(prompt).toContain("stage");
		expect(prompt).toContain("result");
	});

	it("includes HLTV/Liquipedia search instructions for esports", () => {
		const task = {
			type: "new-config",
			filename: "esports-blast.json",
			config: {
				name: "BLAST Spring 2026",
				sport: "esports",
				events: [],
				norwegianTeams: ["Heroic"],
			},
		};

		const prompt = buildResearchPrompt(task, null);

		expect(prompt).toMatch(/HLTV|Liquipedia|dust2/);
	});

	it("does NOT include bracket schema when sport is not esports", () => {
		const task = {
			type: "new-config",
			filename: "tennis-wimbledon.json",
			config: {
				name: "Wimbledon 2026",
				sport: "tennis",
				events: [],
			},
		};

		const prompt = buildResearchPrompt(task, null);

		// The full esports-specific bracket section should be absent
		expect(prompt).not.toContain("upperBracket");
		expect(prompt).not.toContain("lowerBracket");
		expect(prompt).not.toContain("focusTeamPath");
	});

	it("includes focusTeam from norwegianTeams in esports schema placeholder", () => {
		const task = {
			type: "new-config",
			filename: "esports-major.json",
			config: {
				name: "CS2 Major Spring 2026",
				sport: "esports",
				events: [],
				norwegianTeams: ["100 Thieves"],
			},
		};

		const prompt = buildResearchPrompt(task, null);
		expect(prompt).toContain("100 Thieves");
	});
});

// ─── applyBracketRefresh ─────────────────────────────────────────────────────

describe("applyBracketRefresh()", () => {
	it("merges updated bracket data into the matching tournament", () => {
		const now = new Date("2026-02-25T12:00:00Z");
		const config = {
			name: "CS2 Major 2026",
			sport: "esports",
			autoGenerated: true,
			tournaments: [
				{
					id: "cs2-major-2026",
					name: "CS2 Major 2026",
					startDate: "2026-02-24",
					endDate: "2026-02-28",
					bracket: {
						playoffs: {
							upperBracket: [
								{
									round: "Round 1",
									matches: [{ team1: "NaVi", team2: "FaZe", status: "pending" }],
								},
							],
						},
					},
				},
			],
		};

		const bracketResult = {
			bracket: {
				playoffs: {
					upperBracket: [
						{
							round: "Round 1",
							matches: [
								{ team1: "NaVi", team2: "FaZe", score: "2-0", winner: "NaVi", status: "completed" },
							],
						},
					],
				},
				// focusTeamPath lives at the bracket root, not nested under playoffs
				focusTeamPath: {
					team: "NaVi",
					status: "Upper Bracket Round 2",
					completed: [{ stage: "UB R1", opponent: "FaZe", result: "W 2-0" }],
				},
			},
		};

		const updated = applyBracketRefresh(config, "cs2-major-2026", bracketResult, now);

		const t = updated.tournaments[0];
		expect(t.bracket.playoffs.upperBracket[0].matches[0].winner).toBe("NaVi");
		expect(t.bracket.playoffs.upperBracket[0].matches[0].status).toBe("completed");
		expect(t.bracket.playoffs.upperBracket[0].matches[0].score).toBe("2-0");
		expect(t.bracket.focusTeamPath.team).toBe("NaVi");
	});

	it("updates lastResearched timestamp", () => {
		const now = new Date("2026-02-25T14:30:00Z");
		const config = {
			name: "Test",
			tournaments: [
				{
					id: "test-tourney",
					name: "Test Tourney",
					bracket: { playoffs: {} },
				},
			],
		};

		const updated = applyBracketRefresh(config, "test-tourney", { bracket: { updated: true } }, now);
		expect(updated.lastResearched).toMatch(/2026-02-25/);
	});

	it("returns config unchanged when tournament id is not found", () => {
		const config = {
			name: "Test",
			tournaments: [
				{
					id: "real-tourney",
					name: "Real Tourney",
					bracket: { playoffs: {} },
				},
			],
		};

		const updated = applyBracketRefresh(config, "nonexistent-id", { bracket: { foo: "bar" } });
		expect(updated.tournaments[0].bracket).not.toHaveProperty("foo");
	});

	it("returns config unchanged when tournaments array is missing", () => {
		const config = {
			name: "No Tournaments Config",
			events: [],
		};

		const updated = applyBracketRefresh(config, "some-id", { bracket: { playoffs: {} } });
		expect(updated.tournaments).toBeUndefined();
	});

	it("does not mutate the original config's tournaments array reference", () => {
		const originalBracket = { playoffs: { upperBracket: [] } };
		const config = {
			name: "Test",
			tournaments: [
				{
					id: "t1",
					name: "T1",
					bracket: originalBracket,
				},
			],
		};

		const newBracket = { playoffs: { upperBracket: [{ round: "Final", matches: [] }] } };
		applyBracketRefresh(config, "t1", { bracket: newBracket });

		// The returned updated config should have new bracket
		// but we're testing the function doesn't throw or corrupt
		expect(originalBracket.playoffs.upperBracket).toHaveLength(0);
	});

	it("replaces the entire bracket object with the result bracket", () => {
		const config = {
			name: "Test",
			tournaments: [
				{
					id: "t1",
					name: "T1",
					bracket: {
						groups: { A: { name: "Group A" } },
						playoffs: { format: "Old format" },
					},
				},
			],
		};

		const newBracket = {
			groups: { A: { name: "Group A", result: { "1st": "TeamX" } } },
			playoffs: { format: "New format", upperBracket: [] },
		};

		const updated = applyBracketRefresh(config, "t1", { bracket: newBracket });
		const t = updated.tournaments[0];
		expect(t.bracket.playoffs.format).toBe("New format");
		expect(t.bracket.groups.A.result["1st"]).toBe("TeamX");
	});
});
