// profile-vectors.test.js — freezes the web profile-sync CRDT (docs/js/profile-sync.js)
// against the semantics of ios/Sportivista/Profile/ProfileMerge.swift + ProfileSyncModel.swift.
// The merge must be commutative, idempotent and convergent, respect tombstones,
// and break clock ties deterministically (tombstone → deviceID → payloadKey).
// The codec (deflate-raw + base64url) must round-trip. Pure JS, no network.
//
// A future cross-platform golden (payload strings generated by the real iOS
// ProfileShareCodec, decoded here) is the only thing that proves BYTE-level
// interop; it needs a one-off iOS dump and is tracked as a follow-up. These
// tests prove the JS core is internally correct + convergent.

import { describe, it, expect, beforeAll } from "vitest";
import { createClientSandbox, loadClientScript } from "./helpers/load-client.js";

let S; // the profile-sync globals

beforeAll(() => {
	const sandbox = createClientSandbox();
	// The codec needs a few Web APIs the base sandbox doesn't stub; the merge/store
	// need none of them. Provide the Node globals so both halves run.
	Object.assign(sandbox, {
		TextEncoder, TextDecoder, btoa, atob, Uint8Array, Response, Blob,
		crypto: globalThis.crypto,
		CompressionStream: globalThis.CompressionStream,
		DecompressionStream: globalThis.DecompressionStream,
	});
	loadClientScript(sandbox, "profile-sync.js");
	S = sandbox.window;
});

// --- fixtures ----------------------------------------------------------------
const rule = (id, over = {}) => ({
	rule: {
		entityId: id, entityName: over.entityName || id, sport: over.sport || "football",
		scope: over.scope || null, weight: over.weight == null ? 0.5 : over.weight,
		reason: over.reason || "r", addedAt: "2026-07-20T10:00:00Z", lens: over.lens || { sportAsSuch: {} },
	},
	modifiedAt: over.modifiedAt || "2026-07-20T10:00:00Z",
	deviceID: over.deviceID || "dev-a",
	deleted: over.deleted || false,
});
const stateOf = (rules = [], extra = {}) => ({ rules, episodic: extra.episodic || [], counters: extra.counters || [], facts: extra.facts || [] });
const liveIds = (st) => S.ssLiveRules(st).map((r) => r.entityId).sort();

// --- CRDT laws ---------------------------------------------------------------
describe("ssProfileMerge — CRDT laws", () => {
	it("is commutative (merged is order-independent)", () => {
		const a = stateOf([rule("liverpool", { modifiedAt: "2026-07-20T12:00:00Z" }), rule("carlsen", { sport: "chess" })]);
		const b = stateOf([rule("liverpool", { modifiedAt: "2026-07-20T09:00:00Z", reason: "old" }), rule("rain", { sport: "esports" })]);
		expect(S.ssStableStringify(S.ssProfileMerge(a, b).merged)).toEqual(S.ssStableStringify(S.ssProfileMerge(b, a).merged));
	});

	it("is idempotent (merge(a,a) == dedup(a))", () => {
		const a = stateOf([rule("liverpool"), rule("carlsen", { sport: "chess" })]);
		expect(S.ssStableStringify(S.ssProfileMerge(a, a).merged)).toEqual(S.ssStableStringify(S.ssDeduplicateState(a)));
	});

	it("is convergent — a fresh merge of the outcome yields no more push", () => {
		const a = stateOf([rule("liverpool", { modifiedAt: "2026-07-20T12:00:00Z" })]);
		const b = stateOf([rule("liverpool", { modifiedAt: "2026-07-20T09:00:00Z" }), rule("rain", { sport: "esports" })]);
		const { merged } = S.ssProfileMerge(a, b);
		expect(S.ssPushIsEmpty(S.ssProfileMerge(merged, merged).toPush)).toBe(true);
	});
});

// --- LWW + tombstone ---------------------------------------------------------
describe("LWW + tombstone", () => {
	it("newer modifiedAt wins", () => {
		const older = stateOf([rule("x", { modifiedAt: "2026-07-20T09:00:00Z", reason: "old" })]);
		const newer = stateOf([rule("x", { modifiedAt: "2026-07-20T12:00:00Z", reason: "new" })]);
		expect(S.ssProfileMerge(older, newer).merged.rules[0].rule.reason).toBe("new");
	});

	it("a tombstone replicates — an unfollow on one side removes it from the merge", () => {
		const local = stateOf([rule("x", { modifiedAt: "2026-07-20T10:00:00Z" })]);
		const remote = stateOf([rule("x", { modifiedAt: "2026-07-20T11:00:00Z", deleted: true })]);
		expect(liveIds(S.ssProfileMerge(local, remote).merged)).toEqual([]);
	});

	it("a stale live copy cannot resurrect a newer tombstone", () => {
		const stale = stateOf([rule("x", { modifiedAt: "2026-07-20T12:00:00Z" })]); // live, but OLDER than the delete
		const deletedNewer = stateOf([rule("x", { modifiedAt: "2026-07-20T13:00:00Z", deleted: true })]);
		expect(liveIds(S.ssProfileMerge(stale, deletedNewer).merged)).toEqual([]);
	});

	it("on an exact clock tie, the tombstone wins (don't revive on a coin-flip)", () => {
		const live = stateOf([rule("x", { modifiedAt: "2026-07-20T10:00:00Z", deviceID: "dev-a" })]);
		const dead = stateOf([rule("x", { modifiedAt: "2026-07-20T10:00:00Z", deviceID: "dev-a", deleted: true })]);
		expect(liveIds(S.ssProfileMerge(live, dead).merged)).toEqual([]);
	});

	it("clock+delete tie → higher deviceID wins", () => {
		const a = stateOf([rule("x", { modifiedAt: "2026-07-20T10:00:00Z", deviceID: "dev-a", reason: "A" })]);
		const b = stateOf([rule("x", { modifiedAt: "2026-07-20T10:00:00Z", deviceID: "dev-b", reason: "B" })]);
		expect(S.ssProfileMerge(a, b).merged.rules[0].deviceID).toBe("dev-b");
	});
});

// --- counters (G-counter) ----------------------------------------------------
describe("counters — grow-only G-counter", () => {
	it("merges per-device by MAX; total is the sum", () => {
		const a = stateOf([], { counters: [{ key: "opens", perDevice: { "dev-a": 3, "dev-b": 1 } }] });
		const b = stateOf([], { counters: [{ key: "opens", perDevice: { "dev-a": 2, "dev-b": 5 } }] });
		const merged = S.ssProfileMerge(a, b).merged.counters[0].perDevice;
		expect(merged).toEqual({ "dev-a": 3, "dev-b": 5 });
	});
});

// --- write-time stamping -----------------------------------------------------
describe("ssUpdatingRules / follow / unfollow", () => {
	it("stamps only changed rules; unchanged keep their stamp", () => {
		const st = stateOf([rule("keep", { modifiedAt: "2026-07-01T00:00:00Z" })]);
		const live = S.ssLiveRules(st);
		const next = S.ssUpdatingRules(st, live, "2026-07-20T10:00:00Z", "dev-a");
		expect(next.rules[0].modifiedAt).toBe("2026-07-01T00:00:00Z"); // unchanged → kept
	});

	it("unfollow tombstones once and stops projecting the entity", () => {
		const st = stateOf([rule("x")]);
		const after = S.ssUpdatingRules(st, [], "2026-07-20T11:00:00Z", "dev-a");
		expect(after.rules[0].deleted).toBe(true);
		expect(liveIds(after)).toEqual([]);
	});
});

// --- projection to interests -------------------------------------------------
describe("ssProfileToInterests", () => {
	it("buckets by inferred kind and drops tombstones", () => {
		const st = stateOf([
			rule("team-liverpool", { entityName: "Liverpool" }),
			rule("athlete-carlsen", { entityName: "Carlsen", sport: "chess" }),
			rule("tournament-tdf", { entityName: "Tour de France", sport: "cycling" }),
			rule("athlete-gone", { deleted: true }),
		]);
		const i = S.ssProfileToInterests(st);
		expect(i.alwaysTrack.teams.map((e) => e.name)).toEqual(["Liverpool"]);
		expect(i.alwaysTrack.athletes.map((e) => e.name)).toEqual(["Carlsen"]);
		expect(i.alwaysTrack.tournaments.map((e) => e.name)).toEqual(["Tour de France"]);
	});
});

// --- codec round-trip --------------------------------------------------------
const hasDeflateRaw = typeof globalThis.CompressionStream !== "undefined";
describe.skipIf(!hasDeflateRaw)("codec — deflate-raw + base64url round-trip", () => {
	it("decode(encode(state)) == normalized state", async () => {
		const st = stateOf([rule("liverpool", { entityName: "Liverpool FC" }), rule("carlsen", { sport: "chess" })], {
			facts: [{ id: "f1", entityId: null, sport: "chess", kind: "note", value: "nybegynner", reason: "sa det", updatedAt: "2026-07-20T10:00:00Z", deviceID: "dev-a", deleted: false }],
		});
		const payload = await S.ssProfileEncode(st);
		expect(payload).not.toMatch(/[+/=]/); // URL-safe
		const back = await S.ssProfileDecode(payload);
		expect(S.ssStableStringify(back)).toEqual(S.ssStableStringify(S.ssDeduplicateState(st)));
	});

	it("import MERGES into the local profile", async () => {
		S.ssProfileSave(stateOf([rule("existing", { entityName: "Existing" })]));
		const incoming = stateOf([rule("new-one", { entityName: "New" })]);
		const payload = await S.ssProfileEncode(incoming);
		const res = await S.ssProfileImport(payload);
		expect(res.added).toBe(1);
		expect(liveIds(S.ssProfileLoad())).toEqual(["existing", "new-one"]);
	});
});

// --- link parsing ------------------------------------------------------------
describe("ssProfileParseLink", () => {
	it("extracts the payload from scheme, https-hash, and bare forms", () => {
		expect(S.ssProfileParseLink("sportivista://profile?v=1&d=ABC")).toBe("ABC");
		expect(S.ssProfileParseLink("https://sportivista.com/rediger.html#profile=XYZ")).toBe("XYZ");
		expect(S.ssProfileParseLink("RAWPAYLOAD")).toBe("RAWPAYLOAD");
	});
	it("rejects a newer format version", () => {
		expect(() => S.ssProfileParseLink("sportivista://profile?v=999&d=ABC")).toThrow();
	});
});
