import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import os from "os";
import { resolveCoverageGaps } from "../scripts/resolve-coverage-gaps.js";

function makeTmpDir() {
	return fs.mkdtempSync(path.join(os.tmpdir(), "sportsync-test-"));
}

function makeGapFile(dir, data) {
	const file = path.join(dir, "coverage-gaps.json");
	fs.writeFileSync(file, JSON.stringify(data, null, 2));
	return file;
}

function makeGap(overrides = {}) {
	return {
		id: "champions-league-round-of-16",
		sport: "football",
		type: "tournament",
		matchedPattern: "champions league",
		headlines: ["Champions League Draw Announced", "Champions League Round of 16 Preview", "Champions League Matchday Recap"],
		classification: "actionable",
		confidence: "high",
		suggestedConfigName: "football-tournament-2026.json",
		...overrides,
	};
}

function wrapGaps(gaps) {
	return {
		generatedAt: new Date().toISOString(),
		gaps,
		summary: {
			totalGapsDetected: gaps.length,
			actionableGaps: gaps.filter((g) => g.classification === "actionable").length,
			informationalGaps: gaps.filter((g) => g.classification === "informational").length,
		},
	};
}

describe("resolveCoverageGaps()", () => {
	let tmpDataDir;
	let tmpConfigDir;

	beforeEach(() => {
		tmpDataDir = makeTmpDir();
		tmpConfigDir = makeTmpDir();
	});

	afterEach(() => {
		fs.rmSync(tmpDataDir, { recursive: true, force: true });
		fs.rmSync(tmpConfigDir, { recursive: true, force: true });
	});

	it("creates config for high-confidence actionable gap", () => {
		const gap = makeGap({ confidence: "high" });
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(1);
		expect(result.created[0]).toBe("football-tournament-2026.json");

		// Verify the file was actually written
		const configPath = path.join(tmpConfigDir, "football-tournament-2026.json");
		expect(fs.existsSync(configPath)).toBe(true);

		const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
		expect(config.sport).toBe("football");
		expect(config.context).toBe("champions-league-round-of-16");
		expect(config.autoGenerated).toBe(true);
		expect(config.generatedFrom).toBe("coverage-gap");
		expect(config.headlines).toHaveLength(3);
		expect(config.events).toEqual([]);
		expect(config.location).toBe("TBD");
		expect(config.name).toMatch(/Champions League/);
		expect(config.startDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
		expect(config.endDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
	});

	it("creates config for medium-confidence actionable gap", () => {
		const gap = makeGap({
			confidence: "medium",
			headlines: ["Europa League Draw", "Europa League Preview"],
			id: "europa-league-group-stage",
			matchedPattern: "europa league",
			suggestedConfigName: "football-tournament-2026.json",
		});
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(1);

		const configPath = path.join(tmpConfigDir, "football-tournament-2026.json");
		const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
		expect(config.sport).toBe("football");
		expect(config.autoGenerated).toBe(true);
		expect(config.headlines).toHaveLength(2);
	});

	it("skips low-confidence gaps", () => {
		const gap = makeGap({
			confidence: "low",
			headlines: ["Champions League mention"],
		});
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(0);
		expect(result.logged).toHaveLength(1);
		expect(result.logged[0]).toContain("low confidence");

		// No config file should exist
		const files = fs.readdirSync(tmpConfigDir);
		expect(files).toHaveLength(0);
	});

	it("skips informational gaps", () => {
		const gap = makeGap({
			classification: "informational",
			confidence: "medium",
		});
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(0);
		expect(result.logged).toHaveLength(1);
		expect(result.logged[0]).toContain("informational");

		const files = fs.readdirSync(tmpConfigDir);
		expect(files).toHaveLength(0);
	});

	it("skips if config already exists for that sport+type", () => {
		// Pre-create a config file that matches the gap's sport+type
		const existingConfig = {
			name: "UCL 2026",
			sport: "football",
			events: [],
		};
		fs.writeFileSync(
			path.join(tmpConfigDir, "football-tournament-existing.json"),
			JSON.stringify(existingConfig, null, 2),
		);

		const gap = makeGap({ confidence: "high" });
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(0);
		expect(result.skipped).toHaveLength(1);
		expect(result.skipped[0]).toContain("config already exists");

		// Only the pre-existing file should be in the dir
		const files = fs.readdirSync(tmpConfigDir);
		expect(files).toHaveLength(1);
	});

	it("skips if config exists with matching context", () => {
		const existingConfig = {
			name: "CL Config",
			context: "champions-league-round-of-16",
			events: [],
		};
		fs.writeFileSync(
			path.join(tmpConfigDir, "custom-cl.json"),
			JSON.stringify(existingConfig, null, 2),
		);

		const gap = makeGap({ confidence: "high" });
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(0);
		expect(result.skipped).toHaveLength(1);
	});

	it("returns summary with created count", () => {
		const gaps = [
			makeGap({ confidence: "high", id: "cl-r16", suggestedConfigName: "football-tournament-2026.json" }),
			makeGap({
				confidence: "medium",
				id: "wimbledon-2026",
				sport: "tennis",
				type: "tournament",
				matchedPattern: "wimbledon",
				suggestedConfigName: "tennis-tournament-2026.json",
				headlines: ["Wimbledon Seeds Announced", "Wimbledon Preview"],
			}),
			makeGap({ confidence: "low", id: "some-low" }),
			makeGap({ classification: "informational", confidence: "medium", id: "info-only" }),
		];
		const gapFile = makeGapFile(tmpDataDir, wrapGaps(gaps));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(2);
		expect(result.skipped).toHaveLength(0);
		expect(result.logged).toHaveLength(2); // 1 low + 1 informational
	});

	it("handles missing coverage-gaps.json gracefully", () => {
		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: path.join(tmpDataDir, "nonexistent.json"),
		});

		expect(result.created).toHaveLength(0);
		expect(result.skipped).toHaveLength(0);
		expect(result.logged).toHaveLength(0);
	});

	it("handles empty gaps array", () => {
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([]));

		const result = resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(0);
		expect(result.skipped).toHaveLength(0);
		expect(result.logged).toHaveLength(0);
	});

	it("creates config directory if it does not exist", () => {
		const newConfigDir = path.join(tmpConfigDir, "subdir", "configs");
		expect(fs.existsSync(newConfigDir)).toBe(false);

		const gap = makeGap({ confidence: "high" });
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		const result = resolveCoverageGaps({
			configDir: newConfigDir,
			coverageGapPath: gapFile,
		});

		expect(result.created).toHaveLength(1);
		expect(fs.existsSync(newConfigDir)).toBe(true);
	});

	it("end date is approximately 90 days after start date", () => {
		const gap = makeGap({ confidence: "high" });
		const gapFile = makeGapFile(tmpDataDir, wrapGaps([gap]));

		resolveCoverageGaps({
			configDir: tmpConfigDir,
			coverageGapPath: gapFile,
		});

		const configPath = path.join(tmpConfigDir, "football-tournament-2026.json");
		const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));

		const start = new Date(config.startDate);
		const end = new Date(config.endDate);
		const daysDiff = (end - start) / (1000 * 60 * 60 * 24);
		expect(daysDiff).toBeGreaterThanOrEqual(89);
		expect(daysDiff).toBeLessThanOrEqual(91);
	});
});
