//
//  LaunchMetricsUITests.swift
//  SportivistaUITests
//
//  WP-70 — the cold-start baseline. `XCTApplicationLaunchMetric` relaunches the
//  app several times and records launch duration; run against the deterministic
//  `SPORTIVISTA_DEMO=uitest` harness so the number reflects the app's own startup
//  (seed + first frame), not variable network/live-data work.
//
//  NB on "baseline checked in": the Xcode performance baseline lives inside the
//  .xcodeproj (xcbaselines), which is GENERATED by xcodegen and deliberately NOT
//  committed (ios/.gitignore). So the committed artifact is this test itself —
//  the mechanism that produces the baseline on the PR agent's Mac — and the
//  measured number is recorded in the PR / ios/README, per the WP-70 acceptance.
//

import XCTest

final class LaunchMetricsUITests: XCTestCase {

	func testColdStartLaunchBaseline() {
		let app = XCUIApplication()
		app.launchEnvironment["SPORTIVISTA_DEMO"] = "uitest"
		app.launchEnvironment["SPORTIVISTA_UITEST_STATE"] = "agenda"

		measure(metrics: [XCTApplicationLaunchMetric()]) {
			app.launch()
		}
	}
}
