#!/usr/bin/env node
/**
 * Discover Events — LLM-Powered Discovery Agent
 *
 * Uses Claude CLI with WebSearch to research and populate curated event configs.
 *
 * Trigger conditions (any of):
 * - A config has needsResearch: true
 * - A coverage gap with confidence >= "medium" has no matching config
 * - A config has norwegianAthletes array that hasn't been refreshed in 7+ days
 *
 * Safeguards:
 * - Max 3 discovery tasks per run
 * - Requires CLAUDE_CODE_OAUTH_TOKEN (discovery needs web search)
 * - Validates returned JSON against schema before writing
 * - Keeps autoGenerated: true on all machine-written configs
 * - Adds lastResearched timestamp to track freshness
 */

import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import { readJsonIfExists, writeJsonPretty, rootDataPath, iso, MS_PER_DAY, parseCliJsonOutput } from "./lib/helpers.js";
import { buildVerificationHints } from "./lib/schedule-verifier.js";
import { factCheck, buildFactCheckHints, appendFactCheckHistory } from "./lib/fact-checker.js";
import { LLMClient } from "./lib/llm-client.js";
import { urgencyToRefreshInterval } from "./lib/refresh-urgency.js";
import { filterEventsByFocusTeam } from "./lib/focus-team-filter.js";

const MAX_TASKS_PER_RUN = 3;
const ATHLETE_REFRESH_DAYS = 7;
const EVENT_WINDOW_DAYS = 14;

const defaultConfigDir = path.resolve(process.cwd(), "scripts", "config");

/**
 * Find configs and gaps that need research.
 * Returns a prioritized task list (max MAX_TASKS_PER_RUN).
 */
export function findResearchTasks(configs, coverageGaps, now = new Date(), _urgencyDataOverride = null) {
	const tasks = [];

	// Priority 1: configs with needsResearch flag
	for (const { filename, config } of configs) {
		if (config.needsResearch === true) {
			tasks.push({
				type: "new-config",
				priority: 1,
				filename,
				config,
				reason: "needsResearch flag set",
			});
		}
	}

	// Priority 2: autoGenerated configs with empty events (but no needsResearch yet)
	for (const { filename, config } of configs) {
		if (
			config.autoGenerated === true &&
			(!Array.isArray(config.events) || config.events.length === 0) &&
			!config.needsResearch
		) {
			tasks.push({
				type: "new-config",
				priority: 2,
				filename,
				config,
				reason: "autoGenerated with empty events",
			});
		}
	}

	// Priority 3: stale norwegianAthletes (haven't been refreshed in 7+ days)
	for (const { filename, config } of configs) {
		if (
			Array.isArray(config.norwegianAthletes) &&
			config.norwegianAthletes.length > 0
		) {
			const lastResearched = config.lastResearched
				? new Date(config.lastResearched)
				: null;
			const staleMs = ATHLETE_REFRESH_DAYS * MS_PER_DAY;
			if (!lastResearched || now.getTime() - lastResearched.getTime() > staleMs) {
				// Don't duplicate if already queued
				if (!tasks.some((t) => t.filename === filename)) {
					tasks.push({
						type: "refresh-athletes",
						priority: 3,
						filename,
						config,
						reason: lastResearched
							? `Athletes last refreshed ${lastResearched.toISOString().split("T")[0]}`
							: "Athletes never refreshed",
					});
				}
			}
		}
	}

	// Priority 4: active tournaments needing bracket refresh (esports configs with tournaments array)
	// Refresh interval is driven by urgency scoring (refresh-urgency.json) when available,
	// with a fallback to match-day heuristic (1h match day, 2h otherwise)
	const urgencyData = _urgencyDataOverride || readJsonIfExists(
		path.join(process.env.SPORTSYNC_DATA_DIR || rootDataPath(), "refresh-urgency.json")
	);
	for (const { filename, config } of configs) {
		if (!Array.isArray(config.tournaments)) continue;
		for (const t of config.tournaments) {
			if (!t.bracket || !t.startDate || !t.endDate) continue;
			const start = new Date(t.startDate);
			const end = new Date(t.endDate);
			// Only refresh brackets for tournaments currently active or starting within 2 days
			const refreshWindow = new Date(now.getTime() - 2 * MS_PER_DAY);
			if (end < refreshWindow || start > new Date(now.getTime() + 2 * MS_PER_DAY)) continue;
			const lastResearched = config.lastResearched ? new Date(config.lastResearched) : null;

			// Urgency-aware refresh interval: use urgency score if available, else match-day heuristic
			let bracketRefreshMs;
			let urgencyScore = null;
			const urgencyTarget = urgencyData?.targets?.find(u =>
				u.id.includes(filename) || u.id.includes(t.id)
			);
			if (urgencyTarget) {
				bracketRefreshMs = urgencyToRefreshInterval(urgencyTarget.score);
				urgencyScore = urgencyTarget.score;
			} else {
				// Fallback: 1h on match days, 2h otherwise
				const focusTeam = (t.focusTeam || "").toLowerCase();
				const SIX_HOURS = 6 * 60 * 60 * 1000;
				const isMatchDay = focusTeam && (config.events || []).some(ev => {
					if (!ev.time) return false;
					const evTime = new Date(ev.time).getTime();
					const title = (ev.title || "").toLowerCase();
					return title.includes(focusTeam) && Math.abs(now.getTime() - evTime) < SIX_HOURS;
				});
				bracketRefreshMs = isMatchDay ? 60 * 60 * 1000 : 2 * 60 * 60 * 1000;
			}

			if (lastResearched && now.getTime() - lastResearched.getTime() < bracketRefreshMs) continue;
			if (!tasks.some((x) => x.filename === filename)) {
				const taskEntry = {
					type: "refresh-bracket",
					priority: 4,
					filename,
					config,
					tournament: t,
					reason: `Active tournament bracket refresh: ${t.name}`,
				};
				// Boost priority for high-urgency targets
				if (urgencyScore !== null && urgencyScore >= 0.6) {
					taskEntry.priority = 1;
					taskEntry.reason += ` [urgency ${urgencyScore}]`;
				} else if (urgencyScore !== null && urgencyScore >= 0.3) {
					taskEntry.priority = 2;
					taskEntry.reason += ` [urgency ${urgencyScore}]`;
				}
				tasks.push(taskEntry);
			}
		}
	}

	// Priority 5: coverage gaps with medium+ confidence that have no matching config
	if (coverageGaps?.gaps) {
		const configNames = new Set(configs.map((c) => c.config.context || c.config.name?.toLowerCase()));
		for (const gap of coverageGaps.gaps) {
			if (gap.confidence === "low") continue;
			if (gap.classification !== "actionable") continue;
			const gapId = gap.id || gap.matchedPattern;
			if (configNames.has(gapId)) continue;
			tasks.push({
				type: "coverage-gap",
				priority: 4,
				gap,
				reason: `Coverage gap: ${gap.matchedPattern} (${gap.confidence})`,
			});
		}
	}

	// Priority 6: esports focus-team has no active tournaments — discover new ones.
	// This triggers when all tournaments have ended and no future events exist.
	// 3-day cooldown prevents spamming.
	const TOURNAMENT_DISCOVERY_COOLDOWN_DAYS = 3;
	for (const { filename, config } of configs) {
		const sport = (config.sport || "").toLowerCase();
		if (!sport.includes("esport")) continue;
		const focusTeams = config.norwegianTeams || [];
		if (focusTeams.length === 0) continue;
		// Skip if already queued
		if (tasks.some((t) => t.filename === filename)) continue;

		// Check cooldown (lastResearched must be > 3 days ago)
		const lastResearched = config.lastResearched ? new Date(config.lastResearched) : null;
		if (lastResearched && now.getTime() - lastResearched.getTime() < TOURNAMENT_DISCOVERY_COOLDOWN_DAYS * MS_PER_DAY) continue;

		// Check if there are any active or future tournaments
		const SIX_HOURS = 6 * 60 * 60 * 1000;
		const hasActiveTournaments = (config.tournaments || []).some((t) => {
			if (!t.endDate) return false;
			const end = new Date(t.endDate + "T23:59:59Z");
			return end.getTime() > now.getTime() - SIX_HOURS;
		});
		const hasFutureEvents = (config.events || []).some((ev) => {
			if (!ev.time) return false;
			return new Date(ev.time).getTime() > now.getTime();
		});

		if (!hasActiveTournaments && !hasFutureEvents) {
			tasks.push({
				type: "discover-tournaments",
				priority: 6,
				filename,
				config,
				focusTeams,
				reason: `No active tournaments for ${focusTeams.join(", ")} — discovering new ones`,
			});
		}
	}

	// Sort by priority and take top N
	tasks.sort((a, b) => a.priority - b.priority);
	return tasks.slice(0, MAX_TASKS_PER_RUN);
}

/**
 * Build a research prompt for a discovery task.
 * @param {object} task - Discovery task
 * @param {object} userContext - User preferences
 * @param {string[]} verificationHints - Optional accuracy correction hints from verification history
 */
export function buildResearchPrompt(task, userContext, verificationHints) {
	const now = new Date();
	const windowEnd = new Date(now.getTime() + EVENT_WINDOW_DAYS * MS_PER_DAY);
	const windowStr = `${now.toISOString().split("T")[0]} to ${windowEnd.toISOString().split("T")[0]}`;

	if (task.type === "refresh-athletes") {
		return `You are a sports research assistant. Your job is to verify and update athlete rosters.

TASK: Refresh Norwegian athletes for "${task.config.name}" (${task.config.sport || "unknown sport"})
CURRENT ATHLETES: ${JSON.stringify(task.config.norwegianAthletes)}

INSTRUCTIONS:
1. Search for current Norwegian athletes competing in this event
2. Check for retirements, nationality changes, or new qualifiers
3. Return ONLY valid JSON matching this schema:
{
  "norwegianAthletes": ["Name 1", "Name 2"],
  "changes": ["Added X (new qualifier)", "Removed Y (retired)"]
}
4. If no changes needed, return the same list with empty changes array
5. Only include athletes who are currently active and Norwegian

Return ONLY the JSON object, no markdown fences.`;
	}

	if (task.type === "discover-tournaments") {
		const focusTeams = task.focusTeams || task.config?.norwegianTeams || [];
		const focusTeamStr = focusTeams.join(", ") || "the focus team";
		const lookAheadEnd = new Date(now.getTime() + 60 * MS_PER_DAY);
		const lookAheadStr = `${now.toISOString().split("T")[0]} to ${lookAheadEnd.toISOString().split("T")[0]}`;
		return `You are an esports research assistant. Your job is to find upcoming tournaments a team is competing in.

TASK: Find upcoming CS2 tournaments for "${focusTeamStr}"
CURRENT CONFIG: ${JSON.stringify(task.config, null, 2)}

INSTRUCTIONS:
1. Search HLTV.org, Liquipedia, and dust2.us for upcoming CS2 tournaments ${focusTeamStr} is registered, invited, or qualified for in the next 60 days (${lookAheadStr})
2. Include ONLY tournaments where ${focusTeamStr} is confirmed to participate
3. For each tournament include: name, dates, tier, venue, format, prize pool
4. Return ONLY valid JSON matching this schema:
{
  "tournaments": [
    {
      "id": "tournament-id-slug",
      "name": "Tournament Name",
      "organizer": "Organizer",
      "tier": "S-Tier/A-Tier/B-Tier",
      "venue": "Venue, City, Country (or Online)",
      "prizePool": "$100,000 USD",
      "startDate": "2026-03-15",
      "endDate": "2026-03-25",
      "teams": 16,
      "format": "Groups → Double Elimination Playoffs",
      "focusTeam": "${focusTeams[0] || ""}",
      "focusTeamRoster": ["player1", "player2", "player3", "player4", "player5"],
      "coach": "Coach Name"
    }
  ],
  "events": []
}
5. If no upcoming tournaments are found, return empty arrays
6. Use lowercase slugs for tournament IDs (e.g., "blast-spring-2026")

Return ONLY the JSON object, no markdown fences.`;
	}

	const configJson = task.config
		? JSON.stringify(task.config, null, 2)
		: JSON.stringify(task.gap || {}, null, 2);

	if (task.type === "refresh-bracket") {
		const t = task.tournament;
		const focusTeam = t.focusTeam || task.config.norwegianTeams?.[0] || "";
		return `You are a sports research assistant. Your job is to find accurate, current tournament bracket data.

TASK: Refresh bracket for "${t.name}" (esports/CS2)
FOCUS TEAM: ${focusTeam}
CURRENT BRACKET: ${JSON.stringify(t.bracket, null, 2)}

INSTRUCTIONS:
1. Search HLTV, Liquipedia, or dust2.us for the latest bracket results for "${t.name}"
2. Focus on matches involving ${focusTeam} — find their current position and upcoming opponents
3. Update completed matches with winners and scores
4. Fill in TBD slots where teams have been determined
5. Update the focusTeamPath with latest results and next match info
6. Return ONLY valid JSON matching this schema:
{
  "bracket": {
    "groups": { ... },
    "playoffs": {
      "format": "Double Elimination (Bo3)",
      "upperBracket": [{ "round": "Round 1", "matches": [{ "team1": "...", "team2": "...", "score": "2-0", "winner": "...", "status": "completed|live|scheduled|pending" }] }],
      "lowerBracket": [{ "round": "Round 1", "matches": [...] }],
      "grandFinal": { "matches": [...] }
    },
    "focusTeamPath": {
      "team": "${focusTeam}",
      "status": "Current stage description",
      "completed": [{ "stage": "...", "opponent": "...", "result": "W 13-3", "map": "Ancient" }],
      "current": { "stage": "...", "opponent": "...", "format": "Bo3", "status": "live|scheduled" },
      "ifWin": "Description of next match if they win",
      "ifLose": "Description of what happens if they lose"
    }
  }
}
7. For match status use: "completed" (done), "live" (in progress), "scheduled" (time set), "pending" (TBD)
8. Include scores as "2-0", "13-6", "FF" (forfeit), etc.

Return ONLY the JSON object, no markdown fences.`;
	}

	const sportHint = task.config?.sport || task.gap?.sport || "unknown";
	const nameHint = task.config?.name || task.gap?.matchedPattern || "Unknown Event";

	const userInterests = userContext
		? `\nUSER INTERESTS: ${JSON.stringify(userContext)}`
		: "";

	const accuracySection = Array.isArray(verificationHints) && verificationHints.length > 0
		? `\n\nACCURACY CORRECTIONS:\n${verificationHints.join("\n")}`
		: "";

	// Esports-specific schema includes bracket data, format, stage, and result
	const isEsports = sportHint === "esports" || sportHint === "cs2";
	const focusTeams = task.config?.norwegianTeams || userContext?.favoriteEsportsOrgs || [];
	const esportsBracketSchema = isEsports ? `
  "tournaments": [
    {
      "id": "tournament-id",
      "name": "Tournament Name",
      "organizer": "Org Name",
      "tier": "S-Tier/A-Tier/B-Tier",
      "venue": "Venue, City, Country",
      "prizePool": "$100,000 USD",
      "startDate": "2026-06-10",
      "endDate": "2026-06-20",
      "teams": 16,
      "format": "GSL Groups → Double Elimination Playoffs",
      "focusTeam": "${focusTeams[0] || ""}",
      "focusTeamRoster": ["player1", "player2"],
      "coach": "Coach Name",
      "bracket": {
        "groups": { "A": { "name": "Group A", "format": "GSL (Bo1)", "matches": [...], "result": { "1st": "...", "2nd": "..." } } },
        "playoffs": {
          "format": "Double Elimination (Bo3)",
          "upperBracket": [{ "round": "Round 1", "matches": [{ "team1": "...", "team2": "...", "score": "2-0", "winner": "...", "status": "completed" }] }],
          "lowerBracket": [...],
          "grandFinal": { "matches": [...] }
        },
        "focusTeamPath": {
          "team": "${focusTeams[0] || ""}",
          "status": "Current bracket position",
          "completed": [{ "stage": "...", "opponent": "...", "result": "W 13-3", "map": "Ancient" }],
          "current": { "stage": "...", "opponent": "...", "format": "Bo3", "status": "scheduled" },
          "ifWin": "Next match description",
          "ifLose": "Elimination or lower bracket"
        }
      }
    }
  ],` : "";

	const esportsEventFields = isEsports ? `
      "format": "Bo1|Bo3|Bo5",
      "stage": "Group B - Opening Match|Upper Bracket - Round 1|etc.",
      "result": { "winner": "Team A", "score": "2-0", "maps": [{ "map": "Ancient", "team1Score": 13, "team2Score": 6 }] },` : "";

	const esportsFocusInstructions = isEsports && focusTeams.length > 0 ? `
8. FOCUS: Only include matches involving ${focusTeams.join(" or ")} — these are the user's favorite teams
9. For each match include format (Bo1/Bo3/Bo5), stage, and result if completed
10. If the tournament uses brackets (upper/lower, double elimination), include full bracket data in the tournaments array
11. Search HLTV.org, Liquipedia, and dust2.us for accurate bracket and result data` : "";

	return `You are a sports research assistant. Your job is to find accurate, current schedule data.

TASK: Research "${nameHint}" (${sportHint})
EXISTING CONFIG: ${configJson}${userInterests}

INSTRUCTIONS:
1. Search for the official schedule of this event
2. Find all Norwegian athletes/teams competing
3. Return ONLY valid JSON matching this schema:
{
  "events": [
    {
      "title": "Event name",
      "time": "2026-06-15T21:00:00+02:00",
      "venue": "Venue name",
      "norwegian": true,
      "norwegianPlayers": [{"name": "Player Name"}],
      "streaming": [{"platform": "NRK", "type": "tv"}],${esportsEventFields}
    }
  ],${esportsBracketSchema}
  "norwegianAthletes": ["Name 1", "Name 2"],
  "location": "City, Country",
  "startDate": "2026-06-10",
  "endDate": "2026-06-20"
}
4. Use ISO 8601 times with timezone offset (e.g., 2026-06-15T21:00:00+02:00)
5. Only include events in the window ${windowStr} (skip far-future events)
6. For athletes, verify current nationality and retirement status
7. For streaming, check if NRK, TV2, Eurosport, or Viaplay broadcast this event in Norway${esportsFocusInstructions}

Return ONLY the JSON object, no markdown fences.${accuracySection}`;
}

/**
 * Parse and validate a discovery result from Claude CLI.
 */
export function parseDiscoveryResult(raw) {
	let parsed;
	try {
		parsed = JSON.parse(raw);
	} catch {
		// Try extracting from markdown fences
		const match = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
		if (match) {
			parsed = JSON.parse(match[1].trim());
		} else {
			throw new Error(`Could not parse JSON from discovery result`);
		}
	}

	// Validate events array if present
	if (parsed.events) {
		if (!Array.isArray(parsed.events)) {
			throw new Error("events must be an array");
		}
		for (const event of parsed.events) {
			if (!event.title || typeof event.title !== "string") {
				throw new Error("Each event must have a title string");
			}
			if (!event.time || typeof event.time !== "string") {
				throw new Error("Each event must have a time string");
			}
			// Validate time is parseable
			if (isNaN(new Date(event.time).getTime())) {
				throw new Error(`Invalid time: ${event.time}`);
			}
		}
	}

	// Validate norwegianAthletes if present
	if (parsed.norwegianAthletes && !Array.isArray(parsed.norwegianAthletes)) {
		throw new Error("norwegianAthletes must be an array");
	}

	return parsed;
}

/**
 * Sync per-event norwegianPlayers with the top-level roster.
 * Removes players from events who are no longer in the roster.
 */
export function syncEventPlayers(config) {
	if (!Array.isArray(config.norwegianAthletes) || !Array.isArray(config.events)) return;
	const roster = new Set(config.norwegianAthletes.map((n) => n.toLowerCase()));
	for (const event of config.events) {
		if (!Array.isArray(event.norwegianPlayers)) continue;
		event.norwegianPlayers = event.norwegianPlayers.filter(
			(p) => roster.has(p.name.toLowerCase())
		);
		if (event.norwegianPlayers.length === 0 && event.norwegian === true) {
			event.norwegian = false;
		}
	}
}

/**
 * Apply discovery results to a config, preserving autoGenerated flag.
 */
export function applyDiscovery(config, result, now = new Date(), userContext = null) {
	const updated = { ...config };

	if (Array.isArray(result.events) && result.events.length > 0) {
		// Focus-team filter: belt-and-suspenders validation for LLM-generated events.
		// The prompt already asks for focus-team-only, but LLM output isn't guaranteed.
		const { filtered, removedCount } = filterEventsByFocusTeam(result.events, config, userContext);
		if (removedCount > 0) {
			console.log(`  Discovery: focus-team filter removed ${removedCount} non-focus-team events`);
		}
		updated.events = filtered;
		updated.needsResearch = false;
	}

	if (Array.isArray(result.norwegianAthletes) && result.norwegianAthletes.length > 0) {
		updated.norwegianAthletes = result.norwegianAthletes;
	}

	if (result.location && result.location !== "TBD") {
		updated.location = result.location;
	}

	if (result.startDate) {
		updated.startDate = result.startDate;
	}

	if (result.endDate) {
		updated.endDate = result.endDate;
	}

	// Merge tournament bracket data
	if (Array.isArray(result.tournaments) && result.tournaments.length > 0) {
		updated.tournaments = result.tournaments;
	}

	updated.lastResearched = iso(now);
	updated.autoGenerated = true;

	return updated;
}

/**
 * Apply bracket refresh results to a tournament in the config.
 */
export function applyBracketRefresh(config, tournamentId, bracketResult, now = new Date()) {
	const updated = { ...config };
	if (!Array.isArray(updated.tournaments)) return updated;
	const t = updated.tournaments.find((x) => x.id === tournamentId);
	if (!t) return updated;
	if (bracketResult.bracket) {
		t.bracket = bracketResult.bracket;
	}
	updated.lastResearched = iso(now);
	return updated;
}

/**
 * Invoke Claude CLI with a prompt for web-search-enabled discovery.
 */
async function discoverWithClaudeCLI(prompt) {
	const dataDir = rootDataPath();
	const tmpFile = path.join(dataDir, ".discovery-prompt.tmp");
	fs.writeFileSync(tmpFile, prompt);
	try {
		const cmd = `cat "${tmpFile}" | npx -y @anthropic-ai/claude-code@latest -p --output-format json --max-turns 8 --allowedTools "WebSearch" "WebFetch"`;
		const output = execSync(cmd, {
			encoding: "utf-8",
			timeout: 180000,
			maxBuffer: 2 * 1024 * 1024,
		});
		const parsed = parseCliJsonOutput(output);
		return { content: parsed.result, usage: { ...parsed.usage, tracked: true, estimated: false } };
	} finally {
		try { fs.unlinkSync(tmpFile); } catch {}
	}
}

/**
 * Load all event configs from the config directory.
 */
function loadConfigs(configDir) {
	if (!fs.existsSync(configDir)) return [];
	const configs = [];
	for (const file of fs.readdirSync(configDir).filter((f) => f.endsWith(".json"))) {
		if (file === "user-context.json") continue;
		const config = readJsonIfExists(path.join(configDir, file));
		if (!config || Array.isArray(config)) continue; // Skip roster files
		if (typeof config.name !== "string") continue;
		configs.push({ filename: file, config });
	}
	return configs;
}

/**
 * Main discovery orchestrator.
 */
export async function runDiscovery({ configDir, dataDir, now } = {}) {
	const cfgDir = configDir || defaultConfigDir;
	const dDir = dataDir || rootDataPath();
	const timestamp = now || new Date();

	const log = { timestamp: iso(timestamp), tasks: [], skipped: null, tokenUsage: null };

	// Check for Claude CLI token
	if (!process.env.CLAUDE_CODE_OAUTH_TOKEN) {
		console.log("No CLAUDE_CODE_OAUTH_TOKEN — skipping discovery (requires web search).");
		log.skipped = "No CLAUDE_CODE_OAUTH_TOKEN";
		return log;
	}

	const configs = loadConfigs(cfgDir);
	const coverageGaps = readJsonIfExists(path.join(dDir, "coverage-gaps.json"));
	const userContext = readJsonIfExists(path.join(cfgDir, "user-context.json"));

	// Load verification history for accuracy hints
	const verificationHistory = readJsonIfExists(path.join(dDir, "verification-history.json"));
	const { hints: verificationHints } = buildVerificationHints(verificationHistory);
	if (verificationHints.length > 0) {
		console.log(`Injecting ${verificationHints.length} accuracy correction(s) from verification history`);
	}

	// Load fact-check history for accuracy hints
	const factCheckHistoryPath = path.join(dDir, "fact-check-history.json");
	const factCheckHistoryData = readJsonIfExists(factCheckHistoryPath) || [];
	const { hints: fcHints } = buildFactCheckHints(factCheckHistoryData);
	const allVerificationHints = [...verificationHints, ...fcHints];
	if (fcHints.length > 0) {
		console.log(`Injecting ${fcHints.length} fact-check hint(s) from history`);
	}

	// Load reference data for fact-checking discovered configs
	const allEvents = readJsonIfExists(path.join(dDir, "events.json")) || [];
	const standings = readJsonIfExists(path.join(dDir, "standings.json"));
	const rssDigest = readJsonIfExists(path.join(dDir, "rss-digest.json"));
	const factCheckLlm = new LLMClient();

	const tasks = findResearchTasks(configs, coverageGaps, timestamp);

	if (tasks.length === 0) {
		console.log("No discovery tasks needed — all configs are up to date.");
		log.skipped = "No tasks needed";
		return log;
	}

	console.log(`Found ${tasks.length} discovery task(s):`);

	let totalInput = 0;
	let totalOutput = 0;
	let totalCostUSD = 0;
	let totalCalls = 0;

	for (const task of tasks) {
		const taskLog = {
			type: task.type,
			target: task.filename || task.gap?.matchedPattern || "unknown",
			reason: task.reason,
			outcome: "pending",
		};
		log.tasks.push(taskLog);

		console.log(`\n  Researching: ${taskLog.target} (${task.reason})`);

		try {
			const prompt = buildResearchPrompt(task, userContext, allVerificationHints);
			totalCalls++;
			const cliResult = await discoverWithClaudeCLI(prompt);
			totalInput += cliResult.usage.input;
			totalOutput += cliResult.usage.output;
			totalCostUSD += cliResult.usage.costUSD || 0;
			const result = parseDiscoveryResult(cliResult.content);

			if (task.type === "refresh-athletes") {
				// Apply athlete refresh to existing config
				const configPath = path.join(cfgDir, task.filename);
				const currentConfig = readJsonIfExists(configPath);
				if (currentConfig && result.norwegianAthletes) {
					currentConfig.norwegianAthletes = result.norwegianAthletes;
					currentConfig.lastResearched = iso(timestamp);
					syncEventPlayers(currentConfig);
					writeJsonPretty(configPath, currentConfig);
					taskLog.outcome = "success";
					taskLog.changes = result.changes || [];
					console.log(`  Updated athletes in ${task.filename}`);
				}
			} else if (task.type === "new-config" && task.filename) {
				// Apply discovery to existing skeleton config
				const configPath = path.join(cfgDir, task.filename);
				const updated = applyDiscovery(task.config, result, timestamp, userContext);
				writeJsonPretty(configPath, updated);
				taskLog.outcome = "success";
				taskLog.eventsFound = updated.events?.length || 0;
				console.log(`  Populated ${task.filename} with ${taskLog.eventsFound} events`);
			} else if (task.type === "refresh-bracket" && task.filename && task.tournament) {
				// Refresh bracket data for an active tournament
				const configPath = path.join(cfgDir, task.filename);
				const currentConfig = readJsonIfExists(configPath);
				if (currentConfig && result.bracket) {
					const refreshed = applyBracketRefresh(currentConfig, task.tournament.id, result, timestamp);
					writeJsonPretty(configPath, refreshed);
					taskLog.outcome = "success";
					taskLog.bracketUpdated = true;
					console.log(`  Updated bracket for ${task.tournament.name} in ${task.filename}`);
				}
			} else if (task.type === "coverage-gap") {
				// Create new config from coverage gap research
				const gap = task.gap;
				const filename = gap.suggestedConfigName || `${gap.sport}-${gap.type}-${new Date().getFullYear()}.json`;
				const newConfig = applyDiscovery(
					{
						name: result.name || gap.matchedPattern || filename.replace(".json", ""),
						sport: gap.sport,
						context: gap.id,
						autoGenerated: true,
						generatedFrom: "discovery",
						events: [],
					},
					result,
					timestamp,
					userContext,
				);
				const configPath = path.join(cfgDir, filename);
				writeJsonPretty(configPath, newConfig);
				taskLog.outcome = "success";
				taskLog.filename = filename;
				taskLog.eventsFound = result.events?.length || 0;
				console.log(`  Created ${filename} with ${taskLog.eventsFound} events`);
			} else if (task.type === "discover-tournaments" && task.filename) {
				// Merge discovered tournaments into existing config (deduplicated by ID)
				const configPath = path.join(cfgDir, task.filename);
				const currentConfig = readJsonIfExists(configPath);
				if (currentConfig && Array.isArray(result.tournaments) && result.tournaments.length > 0) {
					const existingIds = new Set((currentConfig.tournaments || []).map((t) => t.id));
					const newTournaments = result.tournaments.filter((t) => t.id && !existingIds.has(t.id));
					if (newTournaments.length > 0) {
						currentConfig.tournaments = [...(currentConfig.tournaments || []), ...newTournaments];
						currentConfig.lastResearched = iso(timestamp);
						writeJsonPretty(configPath, currentConfig);
						taskLog.outcome = "success";
						taskLog.tournamentsFound = newTournaments.length;
						console.log(`  Discovered ${newTournaments.length} new tournament(s) for ${task.focusTeams?.join(", ") || "focus team"}`);
					} else {
						taskLog.outcome = "success";
						taskLog.tournamentsFound = 0;
						currentConfig.lastResearched = iso(timestamp);
						writeJsonPretty(configPath, currentConfig);
						console.log(`  No new tournaments found (all already known)`);
					}
				} else {
					taskLog.outcome = "success";
					taskLog.tournamentsFound = 0;
					if (currentConfig) {
						currentConfig.lastResearched = iso(timestamp);
						writeJsonPretty(configPath, currentConfig);
					}
					console.log(`  No tournaments found for ${task.focusTeams?.join(", ") || "focus team"}`);
				}
			}
			// Fact-check discovered events (best-effort)
			if (Array.isArray(result.events) && result.events.length > 0 && factCheckLlm.isAvailable()) {
				try {
					const factResult = await factCheck({
						items: result.events,
						itemType: "config-events",
						context: { events: allEvents, standings, rssDigest },
						llm: factCheckLlm,
					});
					if (factResult.issuesFound > 0) {
						console.log(`  Fact-check: ${factResult.issuesFound} issue(s) in ${taskLog.target}`);
						for (const f of factResult.findings) console.log(`    ${f.severity}: ${f.message}`);
					}
					taskLog.factCheck = { issues: factResult.issuesFound, findings: factResult.findings };
					appendFactCheckHistory(factCheckHistoryPath, {
						...factResult,
						itemType: "config-events",
					});
				} catch (fcErr) {
					console.warn(`  Fact-check failed (non-blocking): ${fcErr.message}`);
				}
			}
		} catch (err) {
			taskLog.outcome = "failed";
			taskLog.error = err.message;
			console.error(`  Failed: ${err.message}`);
		}
	}

	const succeeded = log.tasks.filter((t) => t.outcome === "success").length;
	const failed = log.tasks.filter((t) => t.outcome === "failed").length;

	log.tokenUsage = {
		input: totalInput,
		output: totalOutput,
		calls: totalCalls,
		total: totalInput + totalOutput,
		costUSD: totalCostUSD,
		tracked: true,
		estimated: false,
	};

	// Write discovery token usage to ai-quality.json
	const qualityPath = path.join(dDir, "ai-quality.json");
	const existingQuality = readJsonIfExists(qualityPath) || {};
	writeJsonPretty(qualityPath, {
		...existingQuality,
		discovery: {
			...existingQuality.discovery,
			tokenUsage: log.tokenUsage,
			lastRun: iso(timestamp),
			tasksExecuted: totalCalls,
			succeeded,
			failed,
		},
	});

	console.log(`\nDiscovery complete: ${succeeded} succeeded, ${failed} failed`);

	return log;
}

/**
 * Update dynamic athletes in user-context.json if configured.
 */
async function refreshDynamicAthletes(configDir, userContext) {
	if (!userContext?.dynamicAthletes) return;
	if (!process.env.CLAUDE_CODE_OAUTH_TOKEN) return;

	for (const [sport, settings] of Object.entries(userContext.dynamicAthletes)) {
		if (!settings.norwegian) continue;
		const refreshDays = settings.refreshDays || 14;
		const lastRefresh = settings.lastRefreshed ? new Date(settings.lastRefreshed) : null;
		if (lastRefresh && Date.now() - lastRefresh.getTime() < refreshDays * MS_PER_DAY) {
			continue;
		}

		console.log(`Refreshing dynamic Norwegian athletes for ${sport}...`);
		try {
			const prompt = `You are a sports research assistant. Search for the top current Norwegian ${sport} players/athletes.

Return ONLY valid JSON: { "athletes": ["Name 1", "Name 2", ...] }
Include only currently active, professional Norwegian athletes. Max 10.
No markdown fences.`;
			const cliResult = await discoverWithClaudeCLI(prompt);
			const result = parseDiscoveryResult(cliResult.content);
			if (Array.isArray(result.athletes) && result.athletes.length > 0) {
				// Update favoritePlayers with discovered athletes
				const existing = new Set(userContext.favoritePlayers || []);
				for (const athlete of result.athletes) {
					existing.add(athlete);
				}
				userContext.favoritePlayers = [...existing];
				userContext.dynamicAthletes[sport].lastRefreshed = iso();
				writeJsonPretty(path.join(configDir, "user-context.json"), userContext);
				console.log(`  Added ${result.athletes.length} ${sport} athletes`);
			}
		} catch (err) {
			console.error(`  Failed to refresh ${sport} athletes:`, err.message);
		}
	}
}

/**
 * Write discovery log to data directory.
 */
function writeDiscoveryLog(log, dataDir) {
	const logPath = path.join(dataDir, "discovery-log.json");
	const existing = readJsonIfExists(logPath) || { runs: [] };
	existing.runs.push(log);
	// Keep last 50 runs
	while (existing.runs.length > 50) existing.runs.shift();
	writeJsonPretty(logPath, existing);
}

async function main() {
	console.log("Running event discovery...");
	const cfgDir = defaultConfigDir;
	const dDir = rootDataPath();

	const log = await runDiscovery({ configDir: cfgDir, dataDir: dDir });
	writeDiscoveryLog(log, dDir);

	// Also refresh dynamic athletes if configured
	const userContext = readJsonIfExists(path.join(cfgDir, "user-context.json"));
	if (userContext) {
		await refreshDynamicAthletes(cfgDir, userContext);
	}
}

if (process.argv[1]?.includes("discover-events")) {
	main().catch((err) => {
		console.error("Event discovery failed:", err);
		process.exit(1);
	});
}
