#!/usr/bin/env node
/**
 * Recipe Learner — LLM-Powered Recipe Discovery & Self-Repair
 *
 * Two modes:
 *   1. Learn — Given a URL, the LLM fetches the page, understands the structure,
 *      and produces a recipe JSON that can extract data mechanically.
 *   2. Repair — Given a broken recipe + fresh page content, the LLM updates
 *      the extraction patterns.
 *
 * Budget-limited: max 2 recipe operations per run (matching discovery's MAX_TASKS_PER_RUN pattern).
 * Requires CLAUDE_CODE_OAUTH_TOKEN (uses Claude CLI with web search for learning).
 *
 * Pipeline phase: discover (after discover-events, same cadence)
 *
 * Self-repair escalation (matches schedule-verifier pattern):
 *   Level 0: Mechanical execution (run-recipes.js, every run, zero cost)
 *   Level 1: Static diagnosis (run-recipes.js, zero cost)
 *   Level 2: Pattern mutation (this file, zero cost)
 *   Level 3: LLM re-learning (this file, budget-limited)
 *   Level 4: Source replacement (this file, LLM + web search)
 */

import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import {
	readJsonIfExists,
	writeJsonPretty,
	rootDataPath,
	iso,
	parseCliJsonOutput,
} from "./lib/helpers.js";
import {
	fetchContent,
	extractFromContent,
	validateResults,
	needsRepair,
} from "./lib/recipe-scraper.js";

const MAX_REPAIRS_PER_RUN = 2;
const configDir =
	process.env.SPORTSYNC_CONFIG_DIR ||
	path.resolve(process.cwd(), "scripts", "config");
const recipesDir = path.join(configDir, "recipes");
const dataDir = rootDataPath();
const historyPath = path.join(dataDir, "scraper-history.json");

// ─── Claude CLI invocation (same pattern as discover-events.js) ─────────────

async function invokeClaudeCLI(prompt, maxTurns = 6) {
	const tmpFile = path.join(dataDir, ".recipe-prompt.tmp");
	fs.writeFileSync(tmpFile, prompt);
	try {
		const cmd = `cat "${tmpFile}" | npx -y @anthropic-ai/claude-code@latest -p --output-format json --max-turns ${maxTurns} --allowedTools "WebSearch" "WebFetch"`;
		const output = execSync(cmd, {
			encoding: "utf-8",
			timeout: 180000,
			maxBuffer: 2 * 1024 * 1024,
		});
		const parsed = parseCliJsonOutput(output);
		return { content: parsed.result, usage: parsed.usage };
	} finally {
		try { fs.unlinkSync(tmpFile); } catch {}
	}
}

// ─── Recipe Learning ────────────────────────────────────────────────────────

/**
 * Build a prompt that teaches the LLM to create a recipe from a URL.
 */
function buildLearnPrompt(url, sport, description, sampleContent) {
	const contentPreview = sampleContent
		? sampleContent.substring(0, 3000)
		: "(content will be fetched via WebFetch)";

	return `You are a web scraping expert. Your job is to analyze a web page and create an extraction recipe that can mechanically extract structured data without any LLM involvement.

TARGET URL: ${url}
SPORT: ${sport}
DESCRIPTION: ${description}

${sampleContent ? `PAGE CONTENT SAMPLE (first 3000 chars):
${contentPreview}` : `First, use WebFetch to retrieve the page at: ${url}
Then analyze the HTML structure.`}

Create an extraction recipe JSON with this EXACT structure:
{
  "id": "<short-kebab-case-id>",
  "version": 1,
  "autoGenerated": true,
  "description": "<what this recipe extracts>",
  "source": {
    "urlPattern": "<the URL to fetch>",
    "urlParams": {},
    "responseType": "html",
    "contentType": "html",
    "headers": { "User-Agent": "SportSync/2.0 (https://github.com; sports dashboard)" },
    "timeout": 15000
  },
  "extraction": {
    "splitPattern": "<regex that splits content into repeating blocks, one per data item>",
    "splitType": "regex",
    "fields": [
      {
        "name": "<field name>",
        "selector": "<regex with capture group for the value>",
        "selectorType": "regex",
        "occurrence": 0,
        "transform": "<trim|parseInt|parseFloat|isoDate|multiply:N|prefix:X>",
        "required": true/false,
        "default": "<fallback value if not found>"
      }
    ]
  },
  "output": {
    "mapping": {
      "title": "{field1} vs {field2}",
      "time": "{timestamp|isoDate}",
      "tournament": "{tournament}",
      "venue": "<static or template>",
      "sport": "${sport}"
    }
  },
  "validation": {
    "minResults": 1,
    "maxResults": 200,
    "requiredFields": ["title", "time"],
    "timeRangeCheck": true,
    "freshnessDays": 14
  },
  "health": {
    "consecutiveFailures": 0,
    "maxConsecutiveFailures": 3,
    "successRate": 1.0,
    "lastSuccessCount": 0,
    "avgResultCount": 0
  },
  "metadata": {
    "sport": "${sport}",
    "learnedFrom": "learn-recipe.js"
  }
}

IMPORTANT RULES:
1. The splitPattern MUST be a regex that separates the page into repeating blocks (one per match/event/item)
2. Each field selector MUST be a regex with at least one capture group
3. Use "occurrence" to pick the Nth match when a pattern appears multiple times per block
4. Prefer robust selectors (data attributes, semantic class names) over fragile ones (positional, deeply nested)
5. Test your regex patterns mentally against the page structure
6. Return ONLY valid JSON — no markdown fences, no explanation

Return the recipe JSON:`;
}

/**
 * Build a prompt for repairing a broken recipe.
 */
function buildRepairPrompt(recipe, freshContent, diagnosis) {
	const contentPreview = freshContent.substring(0, 3000);

	return `You are a web scraping expert. A recipe that was extracting data successfully has broken. Repair it.

BROKEN RECIPE:
${JSON.stringify(recipe, null, 2)}

DIAGNOSIS:
- Cause: ${diagnosis.cause}
- Details: ${diagnosis.details.join("; ")}
- Suggestions: ${diagnosis.suggestions.join("; ")}

CURRENT PAGE CONTENT (first 3000 chars):
${contentPreview}

Update the recipe's extraction patterns to work with the current page structure.
Keep the same id, metadata, source, output mapping, and validation.
Only change the extraction block (splitPattern, fields) and increment the version number.

Return ONLY the complete updated recipe JSON — no markdown fences, no explanation.`;
}

/**
 * Parse LLM response to extract recipe JSON.
 */
function parseRecipeResponse(content) {
	if (!content) return null;

	// Try to parse the entire response as JSON
	try {
		return JSON.parse(content.trim());
	} catch {}

	// Try to extract JSON from markdown code blocks
	const jsonMatch = content.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
	if (jsonMatch) {
		try {
			return JSON.parse(jsonMatch[1].trim());
		} catch {}
	}

	// Try to find JSON object in the response
	const objMatch = content.match(/\{[\s\S]*\}/);
	if (objMatch) {
		try {
			return JSON.parse(objMatch[0]);
		} catch {}
	}

	return null;
}

/**
 * Validate a recipe has the required structure.
 */
function isValidRecipe(recipe) {
	if (!recipe?.id) return false;
	if (!recipe?.source?.urlPattern && !recipe?.source?.url) return false;
	if (!recipe?.extraction?.fields?.length) return false;
	if (!recipe?.output?.mapping) return false;
	return true;
}

// ─── Level 2: Pattern Mutation (zero cost) ──────────────────────────────────

/**
 * Try common HTML pattern mutations to fix a broken recipe.
 * Returns fixed recipe or null if no mutation works.
 */
async function tryPatternMutations(recipe) {
	let content;
	try {
		const result = await fetchContent(recipe.source);
		content = result.content;
	} catch {
		return null;
	}

	if (!content) return null;

	const mutations = [
		// Extra whitespace in class names
		(pattern) => pattern.replace(/class="/g, 'class="\\s*'),
		// Attribute order changes — make class matching more flexible
		(pattern) => pattern.replace(/class="([^"]+)"/g, 'class="[^"]*$1[^"]*"'),
		// New wrapper divs — make nesting optional
		(pattern) => pattern.replace(/>([^<]*)</g, ">\\s*$1\\s*<"),
	];

	for (const mutate of mutations) {
		const mutated = { ...recipe, extraction: { ...recipe.extraction } };
		mutated.extraction.splitPattern = mutate(recipe.extraction.splitPattern);

		const items = extractFromContent(content, mutated.extraction);
		if (items.length > 0) {
			const validation = validateResults(items, recipe.validation);
			if (validation.valid) {
				mutated.version = (recipe.version || 1) + 1;
				mutated.lastLearnedAt = new Date().toISOString();
				console.log(`    → Pattern mutation succeeded: ${items.length} results`);
				return mutated;
			}
		}
	}

	return null;
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
	if (!process.env.CLAUDE_CODE_OAUTH_TOKEN) {
		console.log("No CLAUDE_CODE_OAUTH_TOKEN — skipping recipe learning.");
		return;
	}

	const registryPath = path.join(recipesDir, "_registry.json");
	const registry = readJsonIfExists(registryPath);
	if (!registry?.recipes?.length) {
		console.log("No recipes in registry. Skipping.");
		return;
	}

	const history = readJsonIfExists(historyPath) || { runs: [] };
	let repairsPerformed = 0;

	// Find recipes needing repair
	const repairCandidates = registry.recipes.filter((r) => r.needsRepair && r.active);

	if (repairCandidates.length === 0) {
		console.log("No recipes need repair. All healthy.");
		return;
	}

	console.log(`${repairCandidates.length} recipe(s) need repair (budget: ${MAX_REPAIRS_PER_RUN})`);

	for (const entry of repairCandidates) {
		if (repairsPerformed >= MAX_REPAIRS_PER_RUN) {
			console.log(`  Budget exhausted (${MAX_REPAIRS_PER_RUN} repairs). Remaining deferred.`);
			break;
		}

		const recipePath = path.join(recipesDir, entry.file);
		const recipe = readJsonIfExists(recipePath);
		if (!recipe) continue;

		console.log(`  Repairing: ${recipe.id} (${recipe.health?.consecutiveFailures || 0} consecutive failures)`);

		// Level 2: Try pattern mutations first (zero cost)
		const mutated = await tryPatternMutations(recipe);
		if (mutated) {
			writeJsonPretty(recipePath, mutated);
			entry.needsRepair = false;
			entry.consecutiveFailures = 0;
			history.runs.push({
				recipeId: recipe.id,
				timestamp: iso(),
				action: "repair-mutation",
				success: true,
				version: mutated.version,
			});
			console.log(`    → Fixed via pattern mutation (v${mutated.version})`);
			continue;
		}

		// Level 3: LLM re-learning
		console.log(`    → Pattern mutations failed. Invoking LLM re-learning...`);
		try {
			let freshContent = "";
			try {
				const result = await fetchContent(recipe.source);
				freshContent = result.content || "";
			} catch {}

			const diagnosis = {
				cause: "extraction-broken",
				details: [`${recipe.health?.consecutiveFailures || 0} consecutive failures`],
				suggestions: ["Re-learn extraction patterns from current page"],
			};

			const prompt = buildRepairPrompt(recipe, freshContent, diagnosis);
			const cliResult = await invokeClaudeCLI(prompt, 4);
			const repairedRecipe = parseRecipeResponse(cliResult.content);

			if (repairedRecipe && isValidRecipe(repairedRecipe)) {
				// Preserve identity and metadata
				repairedRecipe.id = recipe.id;
				repairedRecipe.metadata = recipe.metadata;
				repairedRecipe.version = (recipe.version || 1) + 1;
				repairedRecipe.lastLearnedAt = new Date().toISOString();
				repairedRecipe.health = {
					...recipe.health,
					consecutiveFailures: 0,
				};

				writeJsonPretty(recipePath, repairedRecipe);
				entry.needsRepair = false;
				entry.consecutiveFailures = 0;
				repairsPerformed++;

				history.runs.push({
					recipeId: recipe.id,
					timestamp: iso(),
					action: "repair-llm",
					success: true,
					version: repairedRecipe.version,
					tokenUsage: cliResult.usage,
				});
				console.log(`    → Repaired via LLM (v${repairedRecipe.version})`);
			} else {
				repairsPerformed++;
				history.runs.push({
					recipeId: recipe.id,
					timestamp: iso(),
					action: "repair-llm",
					success: false,
					reason: "Invalid recipe returned by LLM",
				});
				console.log(`    → LLM repair failed: invalid recipe structure`);
			}
		} catch (error) {
			repairsPerformed++;
			history.runs.push({
				recipeId: recipe.id,
				timestamp: iso(),
				action: "repair-llm",
				success: false,
				reason: error.message,
			});
			console.log(`    → LLM repair failed: ${error.message}`);
		}
	}

	// Save registry and history
	writeJsonPretty(registryPath, registry);
	if (history.runs.length > 200) {
		history.runs = history.runs.slice(-200);
	}
	writeJsonPretty(historyPath, history);

	console.log(`Recipe learner complete: ${repairsPerformed} repair(s) attempted`);
}

// ─── Exports for testing and external use ───────────────────────────────────

export {
	buildLearnPrompt,
	buildRepairPrompt,
	parseRecipeResponse,
	isValidRecipe,
	tryPatternMutations,
};

main().catch((err) => {
	console.error("Recipe learner failed:", err.message);
	process.exit(1);
});
