//
//  Entity.swift
//  Zenji
//
//  WP-11: mirrors docs/data/entities.json — the WP-05 stable-id index of
//  athletes/teams/tournaments/leagues, built by scripts/build-entities.js
//  from tracked.json + norwegian-golfers.json + sports-config.js. This is
//  the lookup table `Event.norwegianPlayers[].entityId` /
//  `homeTeamEntityId` / `awayTeamEntityId` point into.
//

import Foundation

struct Entity: Codable, Equatable, Hashable {
    var id: String
    var name: String
    var aliases: [String]
    var sport: String
    /// "athlete" | "team" | "tournament" | "league" — kept as String rather
    /// than a closed Swift enum; see Event.swift's note on the same choice.
    var type: String
    /// WP-16.2: collision-checked initial-aliases ("Tour de France" → "TdF"),
    /// generated by build-entities.js. Deliberately SEPARATE from `aliases`:
    /// these short acronyms are for the app-side fuzzy resolver only
    /// (EntityIndex.resolve), and are NEVER used by server-side / feed
    /// word-boundary matching. Empty for most entities (only 3+-word names get
    /// one, and only when unambiguous across the index).
    var initials: [String]

    private enum CodingKeys: String, CodingKey { case id, name, aliases, sport, type, initials }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        name = try c.decode(String.self, forKey: .name)
        sport = try c.decode(String.self, forKey: .sport)
        type = try c.decode(String.self, forKey: .type)
        aliases = try c.decodeIfPresent([String].self, forKey: .aliases) ?? []
        initials = try c.decodeIfPresent([String].self, forKey: .initials) ?? []
    }
}
